# Task 5: Mental Health Support Chatbot (Fine-Tuned)

## Objective

The objective of this project is to develop a Mental Health Support Chatbot capable of generating empathetic and supportive responses for users experiencing stress, anxiety, sadness, and emotional challenges.

The chatbot is fine-tuned using DistilGPT2 and an empathy-focused dialogue dataset to learn emotional understanding and supportive communication.

**Dataset:** emotion-emotion_69k.csv  
**Model:** DistilGPT2  
**Framework:** Hugging Face Transformers + Trainer API  
**Environment:** Google Colab

## Cell 1: Install Required Libraries

Purpose: Install all required libraries.

In [1]:
!pip install -q transformers datasets accelerate evaluate sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.3 MB/s eta 0:00:00

## Cell 2: Import Libraries

Purpose: Import required packages.

In [2]:
import pandas as pd
import torch

from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)

## Cell 3: Load Dataset

Purpose: Load uploaded dataset from Google Colab.

In [3]:
df = pd.read_csv('/content/emotion-emotion_69k.csv')

print(df.shape)
df.head()

(64636, 7)

,Unnamed: 0,Situation,emotion,empathetic_dialogues,labels,Unnamed: 5,Unnamed: 6
0,0,I remember going to the fireworks with my best...,sentimental,Customer :I remember going to see the firework...,"Was this a friend you were in love with, or ju...",NaN,NaN
1,1,I remember going to the fireworks with my best...,sentimental,Customer :This was a best friend. I miss her.\...,Where has she gone?,NaN,NaN
2,2,I remember going to the fireworks with my best...,sentimental,Customer :We no longer talk.\nAgent :,Oh was this something that happened because of...,NaN,NaN
3,3,I remember going to the fireworks with my best...,sentimental,Customer :Was this a friend you were in love w...,This was a best friend. I miss her.,NaN,NaN
4,4,I remember going to the fireworks with my best...,sentimental,Customer :Where has she gone?\nAgent :,We no longer talk.,NaN,NaN

## Cell 4: Explore Dataset

Purpose: Understand dataset structure.

In [4]:
print(df.columns)

df[['Situation','emotion','empathetic_dialogues']].head()

Index(['Unnamed: 0', 'Situation', 'emotion', 'empathetic_dialogues', 'labels',
       'Unnamed: 5', 'Unnamed: 6'],
      dtype='object')

,Situation,emotion,empathetic_dialogues
0,I remember going to the fireworks with my best...,sentimental,Customer :I remember going to see the firework...
1,I remember going to the fireworks with my best...,sentimental,Customer :This was a best friend. I miss her.\...
2,I remember going to the fireworks with my best...,sentimental,Customer :We no longer talk.\nAgent :
3,I remember going to the fireworks with my best...,sentimental,Customer :Was this a friend you were in love w...
4,I remember going to the fireworks with my best...,sentimental,Customer :Where has she gone?\nAgent :

## Cell 5: Data Cleaning

Purpose: Remove unnecessary columns and missing values.

In [5]:
df = df[['Situation','emotion','empathetic_dialogues']]

df = df.dropna()

print(df.shape)

(64632, 3)

## Cell 6: Create Training Text

Purpose: Convert records into conversation format.

In [6]:
def create_text(row):

    return (
        f"Emotion: {row['emotion']}\n"
        f"User: {row['Situation']}\n"
        f"Supportive Assistant: {row['empathetic_dialogues']}"
    )

df['text'] = df.apply(create_text, axis=1)

df[['text']].head()

                                                text
0  Emotion: sentimental\nUser: I remember going t...
1  Emotion: sentimental\nUser: I remember going t...
2  Emotion: sentimental\nUser: I remember going t...
3  Emotion: sentimental\nUser: I remember going t...
4  Emotion: sentimental\nUser: I remember going t...

## Cell 7: Reduce Dataset Size

Purpose: Speed up training in Google Colab.

In [7]:
df_small = df.sample(
    n=5000,
    random_state=42
)

print(df_small.shape)

(5000, 4)

## Cell 8: Convert to Hugging Face Dataset

Purpose: Prepare dataset for Trainer API.

In [8]:
dataset = Dataset.from_pandas(
    df_small[['text']]
)

dataset

Dataset({
    features: ['text', '__index_level_0__'],
    num_rows: 5000
})

## Cell 9: Train Test Split

Purpose: Create training and validation sets.

In [9]:
dataset = dataset.train_test_split(
    test_size=0.1
)

dataset

DatasetDict({
    train: Dataset({
        features: ['text', '__index_level_0__'],
        num_rows: 4500
    })
    test: Dataset({
        features: ['text', '__index_level_0__'],
        num_rows: 500
    })
})

## Cell 10: Load DistilGPT2

Purpose: Load tokenizer and model.

In [10]:
model_name = 'distilgpt2'

tokenizer = AutoTokenizer.from_pretrained(model_name)

tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

## Cell 11: Tokenization

Purpose: Convert text into tokens.

In [11]:
def tokenize(example):

    return tokenizer(
        example['text'],
        truncation=True,
        padding='max_length',
        max_length=128
    )

tokenized_dataset = dataset.map(
    tokenize,
    batched=True
)

Map:   0%|          | 0/4500 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

## Cell 12: Data Collator

Purpose: Create batches for language model training.

In [12]:
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

## Cell 13: Training Configuration

Purpose: Configure fine-tuning settings.

In [13]:
training_args = TrainingArguments(

    output_dir="./mental_health_chatbot",

    num_train_epochs=1,

    per_device_train_batch_size=4,

    per_device_eval_batch_size=4,

    logging_steps=100,

    save_steps=500,

    eval_steps=500,

    report_to="none"
)

## Cell 14: Trainer API

Purpose: Initialize Hugging Face Trainer.

In [14]:
trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=tokenized_dataset['train'],

    eval_dataset=tokenized_dataset['test'],

    data_collator=data_collator
)

## Cell 15: Fine Tune Model

Purpose: Train chatbot on empathetic conversations.

In [15]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
[transformers] `loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=1125, training_loss=2.319344512939453, metrics={'train_runtime': 6627.4959, 'train_samples_per_second': 0.679, 'train_steps_per_second': 0.17, 'total_flos': 146979422208000.0, 'train_loss': 2.319344512939453, 'epoch': 1.0})

## Cell 16: Save Model

Purpose: Save trained model.

In [16]:
trainer.save_model('./mental_health_chatbot_model')

tokenizer.save_pretrained(
    './mental_health_chatbot_model'
)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./mental_health_chatbot_model/tokenizer_config.json',
 './mental_health_chatbot_model/tokenizer.json')

## Cell 17: Create Chatbot Function

Purpose: Generate supportive responses.

In [17]:
def generate_response(user_text):

    prompt = f'''
User: {user_text}
Supportive Assistant:
'''

    inputs = tokenizer(
        prompt,
        return_tensors='pt'
    )

    output = model.generate(
        **inputs,
        max_new_tokens=80,
        do_sample=True,
        temperature=0.7,
        top_p=0.9
    )

    return tokenizer.decode(
        output[0],
        skip_special_tokens=True
    )

## Cell 18: Test Chatbot

Purpose: Check chatbot response.

In [18]:
print(
    generate_response(
        'I am feeling stressed because of exams.'
    )
)

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

User: I am feeling stressed because of exams.
Supportive Assistant:
Agent :I am feeling stressed because of exams.
Agent :I am feeling stressed because of exams.
Agent :I am feeling stressed because of exams.
Agent :I am feeling stressed because of exams.
Agent :I am feeling stressed because of exams.
Agent :I am feeling stressed because of exams.
Agent :I am feeling stressed because of exams.
Agent :I

## Cell 19: Interactive CLI Interface

Purpose: Interact with chatbot.

In [19]:
while True:

    user = input('You: ')

    if user.lower() == 'exit':
        break

    print(generate_response(user))

You: I feel lonely these days.

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

User: I feel lonely these days.
Supportive Assistant:
Agent :I feel lonely and lonely when I don't feel like I'm alone
Agent :I feel lonely when I don't feel like I'm alone
Agent :I feel lonely when I don't feel like I'm alone
Agent :I feel lonely when I don't feel like I'm alone
Agent :I feel lonely when I don't feel like I'm alone
Agent :I
You: exit

## Result

- Successfully loaded empathy dataset.
- Fine-tuned DistilGPT2 using Hugging Face Trainer API.
- Generated emotionally supportive responses.
- Developed a functional mental health chatbot.

## Conclusion

A Mental Health Support Chatbot was successfully developed using DistilGPT2 and an empathy-focused dataset.

The model learned emotional conversation patterns and generated supportive responses for user concerns. The project demonstrates fine-tuning of transformer models, conversational AI development, emotional tone design, and chatbot deployment using Hugging Face Transformers.